version: '3.4'

services:
  contactdb:
    image: postgres

  pgadmin:
    image: dpage/pgadmin4

  contact.api:
    image: ${DOCKER_REGISTRY-}contactapi
    build:
      context: .
      dockerfile: Services/Contact/Contact.Api/Dockerfile

volumes:
  postgres_data:
  pgadmin_data: