version: '3.4'

services:
  contactdb:
    container_name: contactdb
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin1234
      - POSTGRES_DB=ContactDb
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  pgadmin:
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=ozcan.caparoglu@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=admin1234
    restart: always
    ports:
        - "5050:80"
    volumes:
      - pgadmin_data:/root/.pgadmin

  contact.api:
    container_name: contact.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:ContactConnectionString=Server=contactdb;Port=5432;Database=ContactDb;User Id=admin;Password=admin1234;"
    depends_on:
      - contactdb
    ports:
      - "8000:80"
